when@dev:
    web_profiler:
        toolbar: false

    framework:
        profiler:
            enabled: false

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
