# Shared variables across all environments

# PHP
php_version: "8.3"
php_extensions:
  - php{{ php_version }}-cli
  - php{{ php_version }}-fpm
  - php{{ php_version }}-pgsql
  - php{{ php_version }}-intl
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-xml
  - php{{ php_version }}-curl
  - php{{ php_version }}-zip

# PostgreSQL
postgresql_version: "17"

# Node.js
nodejs_version: "20"

# Mercure
mercure_version: "0.16.0"
mercure_port: 3000

# Project
project_name: zbbs
repo_root: /opt/zbbs
project_root: /var/www/zbbs
git_repository: "git@github.com:jeffdafoe/zbbs.git"
